---

# The medperf playbook stands for "medium performance"
# The Windows VM is on a dedicated disk for the VM but the PCI controller is "emulated".
# lsw_windows_img_size don't have to be too high. You will expand your drive directly on Windows after installation.
# It gives you a dual boot system with Windows and Linux at boot.
# It gives good performance. It also installs Looking Glass on both Linux host and Windows VM.
# Ninite programs are also installed.
# Note: Looking Glass musts be installed because no 2nd keyboard and mouse are set.
# Adjust the variables with documentation/VARIABLES.md

- name: A man needs a name
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  vars:
    lsw_windows_iso: windows11.iso
    lsw_windows_version: 11
    lsw_windows_img_size: 30G
    lsw_windows_disk_device_path: '/dev/sda'
    lsw_windows_gpu_driver: nvidia
    lsw_passthrough_gpu_pci_base_addr: 01:00
    lsw_windows_install_app_from_ninite: true
    lsw_install_looking_glass: true
  roles:
    - ansible-role-lsw
