---

- name: Create autologin group
  ansible.builtin.group:
    name: autologin
    state: present
  become: true

- name: Add current user to some groups
  ansible.builtin.user:
    name: "{{ ansible_facts.env.LOGNAME }}"
    groups: libvirt,kvm,input,disk,autologin
    append: true
  become: true

- name: Replace libvirt QEMU user
  ansible.builtin.replace:
    path: /etc/libvirt/qemu.conf
    regexp: '^#?\s*user\s*=.*'
    replace: user = "{{ ansible_facts.env.LOGNAME }}"
  notify: Restart libvirt
  become: true

- name: Replace libvirt QEMU group
  ansible.builtin.replace:
    path: /etc/libvirt/qemu.conf
    regexp: '^#?\s*group\s*=.*'
    replace: 'group = "kvm"'
  notify: Restart libvirt
  become: true

- name: Modify cgroup_device_acl block in libvirt QEMU conf
  ansible.builtin.blockinfile:
    path: /etc/libvirt/qemu.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - cgroup_device_acl"
    block: "{{ __lsw_cgroup_acl_block }}"
  notify: Restart libvirt
  become: true

- name: Create scripts for Passthrough
  become: true
  vars:
    _lsw_lg: false
  when: lsw_virt_mode == 'passthrough'
  block:
    - name: Create libvirt hooks folders
      ansible.builtin.file:
        path: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}/{{ (item | split(','))[0] }}/{{ (item | split(','))[1] }}"
        state: directory
        recurse: true
        mode: "0755"
        owner: root
        group: root
      loop:
        - prepare,begin
        - started,begin
        - release,end
    - name: Create Start script for VM
      ansible.builtin.template:
        src: start.sh.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}/prepare/begin/start.sh"
        mode: "0755"
        owner: root
        group: root
    - name: Create dynamic conf for VM second mouse
      ansible.builtin.template:
        src: evdev-mouse.xml.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}/evdev-mouse.xml"
        mode: "0755"
        owner: root
        group: root
      when: lsw_config_usb_mouse != ''
    - name: Create dynamic conf for VM second keyboard
      ansible.builtin.template:
        src: evdev-kbd.xml.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}/evdev-kbd.xml"
        mode: "0755"
        owner: root
        group: root
      when: lsw_config_usb_kbd != ''
    - name: Create Started script for VM
      ansible.builtin.template:
        src: started.sh.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}/started/begin/started.sh"
        mode: "0755"
        owner: root
        group: root
      when: lsw_config_usb_kbd != '' or lsw_config_usb_mouse != ''
    - name: Create Stop script for VM
      ansible.builtin.template:
        src: stop.sh.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}/release/end/stop.sh"
        mode: "0755"
        owner: root
        group: root
    - name: Copy CPU performance script
      ansible.builtin.copy:
        src: cpu_mode_performance.sh
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}/prepare/begin/cpu_mode_performance.sh"
        mode: "0755"
        owner: root
        group: root
    - name: Copy CPU powersave script
      ansible.builtin.copy:
        src: cpu_mode_powersave.sh
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}/release/end/cpu_mode_powersave.sh"
        mode: "0755"
        owner: root
        group: root
    - name: Copy RAM deallocation Hugepages script
      ansible.builtin.copy:
        src: dealloc_hugepages.sh
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}/release/end/dealloc_hugepages.sh"
        mode: "0755"
        owner: root
        group: root
    - name: Create RAM allocation Hugepages script
      ansible.builtin.template:
        src: alloc_hugepages.sh.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}/prepare/begin/alloc_hugepages.sh"
        mode: "0755"
        owner: root
        group: root

- name: Create scripts for Looking Glass VM
  become: true
  vars:
    _lsw_lg: true
  when: lsw_install_looking_glass
  block:
    - name: Create libvirt hooks folders for Looking Glass VM
      ansible.builtin.file:
        path: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}lg/{{ (item | split(','))[0] }}/{{ (item | split(','))[1] }}"
        state: directory
        recurse: true
        mode: "0755"
        owner: root
        group: root
      loop:
        - prepare,begin
        - started,begin
        - release,end
    - name: Create Start script for Looking Glass VM
      ansible.builtin.template:
        src: start.sh.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}lg/prepare/begin/start.sh"
        mode: "0755"
        owner: root
        group: root
    - name: Create dynamic conf for Looking Glass VM second mouse
      ansible.builtin.template:
        src: evdev-mouse.xml.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}lg/evdev-mouse.xml"
        mode: "0755"
        owner: root
        group: root
      when: lsw_config_usb_mouse != ''
    - name: Create dynamic conf for Looking Glass VM second keyboard
      ansible.builtin.template:
        src: evdev-kbd.xml.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}lg/evdev-kbd.xml"
        mode: "0755"
        owner: root
        group: root
      when: lsw_config_usb_kbd != ''
    - name: Create Started script for Looking Glass VM
      ansible.builtin.template:
        src: started.sh.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}lg/started/begin/started.sh"
        mode: "0755"
        owner: root
        group: root
      when: lsw_config_usb_kbd != '' or lsw_config_usb_mouse != ''
    - name: Create Stop script for Looking Glass VM
      ansible.builtin.template:
        src: stop.sh.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}lg/release/end/stop.sh"
        mode: "0755"
        owner: root
        group: root
    - name: Copy CPU performance script for Looking Glass VM
      ansible.builtin.copy:
        src: cpu_mode_performance.sh
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}lg/prepare/begin/cpu_mode_performance.sh"
        mode: "0755"
        owner: root
        group: root
    - name: Copy CPU powersave script for Looking Glass VM
      ansible.builtin.copy:
        src: cpu_mode_powersave.sh
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}lg/release/end/cpu_mode_powersave.sh"
        mode: "0755"
        owner: root
        group: root
    - name: Copy RAM deallocation Hugepages script for Looking Glass VM
      ansible.builtin.copy:
        src: dealloc_hugepages.sh
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}lg/release/end/dealloc_hugepages.sh"
        mode: "0755"
        owner: root
        group: root
    - name: Create RAM allocation Hugepages script for Looking Glass VM
      ansible.builtin.template:
        src: alloc_hugepages.sh.j2
        dest: "/etc/libvirt/hooks/qemu.d/{{ lsw_windows_vm_name }}lg/prepare/begin/alloc_hugepages.sh"
        mode: "0755"
        owner: root
        group: root

- name: Copy QEMU hook manager
  ansible.builtin.copy:
    src: qemu
    dest: /etc/libvirt/hooks/qemu
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Configure Host file share for VM
  become: true
  when: lsw_windows_access_host_files
  block:
    - name: Copy samba configuration
      ansible.builtin.template:
        src: smb.conf.j2
        dest: /etc/samba/smb.conf
        mode: "0640"
        owner: root
        group: root
    - name: Enable and activate samba standalone server
      ansible.builtin.systemd:
        name: smb
        enabled: true
        state: started
    - name: Check if samba user exists
      ansible.builtin.command: pdbedit -L {{ lsw_windows_user }}
      register: _lsw_user_check
      changed_when: false
      failed_when: false
    - name: Add password if samba user does not exist
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          printf "%s\n%s\n" "{{ lsw_windows_access_host_files_pass }}" "{{ lsw_windows_access_host_files_pass }}" \
          | smbpasswd -a -s {{ lsw_windows_user }}
      when: _lsw_user_check.rc != 0
      changed_when: true
      no_log: true
