---

- name: Fail when Distro is not supported
  ansible.builtin.fail:
    msg: "Distribution not supported !!!"
  when: ansible_facts['lsb']['id'] not in ['EndeavourOS','Debian','NobaraLinux']

- name: Fail when Virtualization mode is wrong
  ansible.builtin.fail:
    msg: "Virtualization mode not supported, please set lsw_virt_mode on passthrough or gvtg or sriov !!!"
  when: lsw_virt_mode not in ['passthrough','gvtg','sriov']

- name: Fail when Virtualization mode is wrong for unsupported CPU
  ansible.builtin.fail:
    msg: "Virtualization mode not supported for AMD !!!"
  when: lsw_virt_mode in ['gvtg','sriov'] and __lsw_iommu_param != 'intel_iommu=on'

- name: Fail when Ansible runs with root user
  ansible.builtin.fail:
    msg: "Don't run Ansible with root user, use your personal user !!!"
  when: ansible_user_uid == 0

- name: Fail when driver not Nvidia, Intel or AMD
  ansible.builtin.fail:
    msg: "Driver not supported, it musts be intel (the default even for gvtg or sriov virtualization mode), amd or nvidia !!!"
  when: lsw_windows_gpu_driver not in ['intel','nvidia','amd']

- name: Fail when VM memory exceeds 3/4 of total memory available on Host
  ansible.builtin.fail:
    msg: "VM memory (RAM) too high, host also needs memory !!!"
  when: lsw_config_vm_memory > ( ansible_memtotal_mb * 3 / 4 )

- name: Fail when path to second mouse doesnt exist
  ansible.builtin.fail:
    msg: "Path to second mouse doesn't exist !!!"
  when: lsw_config_usb_mouse != '' and not _lsw_second_mouse.stat.exists

- name: Fail when path to second keyboard doesnt exist
  ansible.builtin.fail:
    msg: "Path to second keyboard doesn't exist !!!"
  when: lsw_config_usb_kbd != '' and not _lsw_second_kbd.stat.exists

- name: Fail when physical disk path is not good
  ansible.builtin.fail:
    msg: "Path to disk for copying built image isn't a disk !!!"
  when: lsw_windows_disk_device_path != '' and _lsw_is_disk.stdout != 'disk'

- name: Fail when missing Windows ISO file for building
  ansible.builtin.fail:
    msg: "{{ role_path }}/files/build/{{ lsw_windows_iso }} doesn't exist, read {{ role_path }}/files/build/README.md !!!"
  when: "'build' in ansible_run_tags and not _lsw_windows_iso.stat.exists"

- name: Fail when missing GPU driver file for building
  ansible.builtin.fail:
    msg: "{{ role_path }}/files/build/extra_packages/gpudriver.exe doesn't exist, read {{ role_path }}/files/build/extra_packages/README.md !!!"
  when: "'build' in ansible_run_tags and not _lsw_gpu_driver.stat.exists"

- name: Fail when missing Virtio ISO file for building
  ansible.builtin.fail:
    msg: "{{ role_path }}/files/build/virtio/virtio-win.iso doesn't exist, read {{ role_path }}/files/build/virtio/README.md !!!"
  when: "'build' in ansible_run_tags and not _lsw_virtio_win.stat.exists"

- name: Fail when missing Ninite Installer file for building
  ansible.builtin.fail:
    msg: "{{ role_path }}/files/build/extra_packages/NiniteInstaller.exe doesn't exist, read {{ role_path }}/files/build/extra_packages/README.md !!!"
  when: "lsw_windows_install_app_from_ninite and 'build' in ansible_run_tags and not _lsw_ninite_file.stat.exists"

- name: Fail when missing Looking Glass driver file for building
  ansible.builtin.fail:
    msg: "{{ role_path }}/files/build/extra_packages/looking_glass_host_setup.exe dont exist, read {{ role_path }}/files/build/extra_packages/README.md !!!"
  when: "lsw_install_looking_glass and 'build' in ansible_run_tags and not _lsw_lg_driver.stat.exists"

- name: Fail when password for the VM not set with RDP activated
  ansible.builtin.fail:
    msg: "Windows VM password cannot be empty !!!"
  when: lsw_windows_activate_rdp and lsw_windows_password == ''

- name: Configure IOMMU for dracut
  ansible.builtin.copy:
    dest: /etc/kernel/cmdline
    content: "{{ ((_lsw_krnl_file.content | b64decode).splitlines() | join(' ') + ' ' + __lsw_iommu_param + ' iommu=pt') | trim }}"
    mode: "0644"
  when: lsw_distro_initramfs_binary == 'dracut' and __lsw_iommu_param not in (_lsw_krnl_file.content | b64decode)
  become: true
  notify:
    - Reload Boot Loader
    - Reload initramfs
    - Reboot
    - Pause

- name: Configure IOMMU for grub2
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=[\"'](.*)[\"']"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 {{ __lsw_iommu_param }} iommu=pt"'
    backrefs: true
  when: lsw_distro_boot_loader == 'grub' and _lsw_grub_check.stdout == 'absent'
  become: true
  notify:
    - Reload Boot Loader
    - Reload initramfs
    - Reboot
    - Pause

- name: Preflight for Passthrough Virtualization mode
  when: lsw_virt_mode == 'passthrough'
  notify:
    - Reload Boot Loader
    - Reload initramfs
    - Reboot
    - Pause
  block:
    - name: Fail if not enough GPU
      ansible.builtin.fail:
        msg: "You need at least 2 GPU !!!"
      when: "_lsw_lspci_output.stdout_lines | select('search', 'VGA') | list | length < 2"
    - name: Fail if no 2nd Keyboard/Mouse and no LookingGlass
      ansible.builtin.fail:
        msg: "VM wont be usable without 2nd Keyboard/Mouse or LookingGlass not enabled !!!"
      when: "not lsw_install_looking_glass and (lsw_config_usb_kbd == '' or lsw_config_usb_mouse == '')"
    - name: Copy initramfs (dracut) options
      ansible.builtin.template:
        src: vfio-dracut.conf.j2
        dest: /etc/dracut.conf.d/vfio.conf
        mode: preserve
      become: true
      when: "'build' in ansible_run_tags and lsw_distro_initramfs_binary == 'dracut'"
    - name: Copy modprobe.d options for vfio
      ansible.builtin.template:
        src: vfio-modprobe.conf.j2
        dest: /etc/modprobe.d/vfio.conf
        mode: preserve
      become: true
      when: "'build' in ansible_run_tags"
    - name: Copy modukes-load.d options for vfio
      ansible.builtin.copy:
        src: vfio-modules.conf
        dest: /etc/modules-load.d/vfio.conf
        mode: preserve
      become: true
      when: "'build' in ansible_run_tags and lsw_distro_initramfs_binary != 'dracut'"

- name: Preflight for GVT-g Virtualization mode
  when: lsw_virt_mode == 'gvtg'
  notify:
    - Reload Boot Loader
    - Reload initramfs
    - Reboot
    - Pause
  block:
    - name: Fail when CPU doesn't support GVT-g
      ansible.builtin.fail:
        msg: "GVT-g virtualization mode is not supported on this CPU !!!"
      when: not 'intel' in __lsw_iommu_param or (__lsw_intel_generation | int) < 6 or (__lsw_intel_generation | int) > 10
    - name: Fail when Looking Glass not enabled
      ansible.builtin.fail:
        msg: "Virtualization mode gvtg needs Looking Glass !!!"
      when: not lsw_install_looking_glass
    - name: Copy modprobe options for i915 module
      ansible.builtin.copy:
        src: i915.gvtg.conf
        dest: /etc/modprobe.d/i915.conf
        mode: "0644"
        owner: root
        group: root
      become: true
    - name: Copy modules to load at boot
      ansible.builtin.copy:
        src: modules.gvtg.conf
        dest: /etc/modules-load.d/gvtg.conf
        mode: "0644"
        owner: root
        group: root
      become: true

- name: Preflight for SR-IOV Virtualization mode
  when: lsw_virt_mode == 'sriov'
  notify:
    - Reload Boot Loader
    - Reload initramfs
    - Reboot
    - Pause
  block:
    - name: Fail when CPU doesn't support SR-IOV
      ansible.builtin.fail:
        msg: "SR-IOV virtualization mode is not supported on this CPU !!!"
      when: not 'intel' in __lsw_iommu_param or (__lsw_intel_generation | int) < 11
    - name: Fail when Looking Glass is disabled
      ansible.builtin.fail:
        msg: "Virtualization mode sriov needs Looking Glass !!!"
      when: not lsw_install_looking_glass
    - name: Copy modprobe options for i915 module
      ansible.builtin.copy:
        src: i915.sriov.conf
        dest: /etc/modprobe.d/i915.conf
        mode: "0644"
        owner: root
        group: root
      become: true
    - name: Copy modules to load at boot
      ansible.builtin.copy:
        src: vfio-modules.conf
        dest: /etc/modules-load.d/sriov.conf
        mode: "0644"
        owner: root
        group: root
      become: true

- name: Force all notified handlers to run at this point
  ansible.builtin.meta: flush_handlers
