---
# /boot for gvtg with arch
# /efi for classic eos
pgs_distro_boot_location: '/efi'

pgs_packages:
  - packer
  - edk2-ovmf
  - qemu-base
  - qemu-common
  - qemu-hw-usb-host
  - qemu-img
  - qemu-system-x86
  - qemu-system-x86-firmware
  - libvirt
  - virt-manager
  - virt-install
  - ebtables
  - dnsmasq
  - downgrade
  - yay
  - python-lxml
  - qemu-audio-pipewire
  - qemu-ui-spice-core
  - qemu-ui-opengl
# Build dependencies
  - python-build
  - python-installer
  - python-pyproject-hooks
  - qemu-ui-gtk

pgs_zen_packages:
  - 'linux-zen=6.12.10.zen1'
  - 'linux-zen-headers=6.12.10.zen1'

pgs_zen_gvtg_packages:
  - 'linux-zen=6.1.12.zen1'
  - 'linux-zen-headers=6.1.12.zen1'

pgs_windows_ovmf_code_path: /usr/share/edk2/x64/OVMF_CODE.4m.fd
pgs_windows_ovmf_vars_path: /usr/share/edk2/x64/OVMF_VARS.4m.fd
