---

- name: Reinstall Kernels
  ansible.builtin.shell:
    cmd: >-
      {{
        'reinstall-kernels'
        if _systemd_boot.stat.exists
        else 'update-grub && update-initramfs -u -k all'
      }}
  changed_when: true
  become: true

- name: Reinstall boot loader with Windows Disk
  ansible.builtin.shell:
    cmd: >-
      {{
        'reinstall-kernels'
        if _systemd_boot.stat.exists
        else
        'sed -i "s/^#.*OS_PROBER.*/GRUB_DISABLE_OS_PROBER=false/" /etc/default/grub ; update-grub ; sed -i "s/^.*OS_PROBER.*/#GRUB_DISABLE_OS_PROBER=false/"'
      }}
  changed_when: true
  become: true

- name: Reboot
  ansible.builtin.shell: |
    nohup bash -c "sleep 10 && shutdown -r now" >/dev/null 2>&1 &
  async: 1
  poll: 0
  ignore_errors: true
  become: true
  changed_when: true

- name: Pause
  ansible.builtin.pause:
    seconds: 15
    prompt: 'The system will now reboot, please re execute the playbook at next startup'

- name: Restart libvirt
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted
  become: true
